"""add language to posts

Revision ID: 298d67b01969
Revises: 9085b64c7125
Create Date: 2020-10-18 15:59:27.525796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '298d67b01969'
down_revision = '9085b64c7125'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
