"""user tokens

Revision ID: 77144ad75a1c
Revises: 24150fed965f
Create Date: 2020-11-24 10:13:20.447390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77144ad75a1c'
down_revision = '24150fed965f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('token_expiration', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_column('user', 'token_expiration')
    op.drop_column('user', 'token')
    # ### end Alembic commands ###
